import { z } from "zod";

export const enquirySchema = z.object({
  customerId: z.string().min(1, "Customer selection is required"),
  customerName: z.string().min(2, "Customer name is required"),
  contactName: z.string().min(2, "Contact name is required"),
  contactEmail: z.string().email("Valid contact email is required"),
  contactPhone: z.string().min(6, "Valid phone number is required"),
  source: z.enum([
    "Email",
    "Phone",
    "Website",
    "Sales Team",
    "Existing Customer",
    "Referral",
    "WhatsApp",
    "Partner",
    "Other",
  ]),
  status: z.enum([
    "New",
    "Under Review",
    "Information Required",
    "Rate Pending",
    "Ready for Quotation",
    "Won",
    "Lost",
    "Cancelled",
  ]),
  priority: z.enum(["Low", "Medium", "High", "Urgent"]),
  assignedTo: z.string().min(2, "Assigned representative is required"),
  origin: z.string().min(2, "Origin location/port is required"),
  originCountry: z.string().min(2, "Origin country is required"),
  destination: z.string().min(2, "Destination location/port is required"),
  destinationCountry: z.string().min(2, "Destination country is required"),
  transportMode: z.enum([
    "Ocean Freight",
    "Air Freight",
    "Road Freight",
    "Rail Freight",
    "Multimodal",
  ]),
  serviceType: z.enum([
    "Freight Forwarding",
    "Transportation",
    "Customs Clearance",
    "Warehousing",
    "Door-to-Door",
    "Port-to-Port",
    "Door-to-Port",
    "Port-to-Door",
    "3PL / Fulfillment",
  ]),
  cargoType: z.enum([
    "General Cargo",
    "Consumer Electronics",
    "Pharmaceuticals",
    "Hazardous / Chemicals",
    "Perishable / Cold Chain",
    "Machinery & Equipment",
    "Garments & Textiles",
    "Auto Parts",
  ]),
  cargoDescription: z.string().min(3, "Cargo description is required"),
  quantity: z.number().min(1, "Quantity must be at least 1"),
  quantityUnit: z.string().min(1, "Quantity unit is required"),
  weightKg: z.number().min(0, "Weight must be non-negative"),
  volumeCbm: z.number().min(0, "Volume must be non-negative"),
  containerType: z.string().min(1, "Container type is required"),
  containerQuantity: z.number().min(1, "Container quantity is required"),
  pickupDate: z.string().min(1, "Pickup date is required"),
  requiredDeliveryDate: z.string().min(1, "Required delivery date is required"),
  incoterm: z.string().min(2, "Incoterm is required"),
  specialRequirements: z.string().optional(),
  notes: z.string().optional(),
});

export type EnquiryFormValues = z.infer<typeof enquirySchema>;
