"use client";

import React, { useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { PageHeader } from "@/components/ui/page-header";
import { StatusBadge } from "@/components/ui/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Tabs } from "@/components/ui/tabs";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Timeline } from "@/components/ui/timeline";
import { QuotationStatus } from "@/types/quotation";
import { useQuotationStore } from "@/store/use-quotation-store";
import { formatCurrency } from "@/lib/utils";
import {
  FileText,
  Send,
  CheckCircle2,
  XCircle,
  Copy,
  Printer,
  Lock,
  ArrowRight,
  ShieldAlert,
  Clock,
  History,
  Building2,
  Calendar,
  DollarSign,
  AlertCircle,
  Briefcase,
} from "lucide-react";
import Link from "next/link";
import { toast } from "sonner";

export default function QuotationDetailPage() {
  const params = useParams();
  const router = useRouter();
  const quotationId = (params.id as string) || "QT-2026-001";

  const { quotations, sendQuotation, approveQuotation, acceptQuotation, rejectQuotation, createRevision } = useQuotationStore();

  const quotation = quotations.find((q) => q.id.toLowerCase() === quotationId.toLowerCase() || q.quotationNumber.toLowerCase() === quotationId.toLowerCase()) || quotations[0];

  const [activeTab, setActiveTab] = useState("preview");

  // Modals & Dialogs
  const [isRejectDialogOpen, setIsRejectDialogOpen] = useState(false);
  const [rejectReason, setRejectReason] = useState("");
  const [isRevisionDialogOpen, setIsRevisionDialogOpen] = useState(false);
  const [revisionReason, setRevisionReason] = useState("");

  if (!quotation) {
    return (
      <div className="p-8 text-center text-slate-400">
        <p>Quotation record not found.</p>
        <Link href="/sales/quotations">
          <Button variant="outline" size="sm" className="mt-4">Back to Quotations</Button>
        </Link>
      </div>
    );
  }

  // Activities log
  const timelineActivities = [
    { id: "1", title: `Quotation ${quotation.quotationNumber} Rev ${quotation.revisionNumber} Created`, description: `Generated by ${quotation.createdBy}`, timestamp: quotation.createdAt, completed: true },
    ...(quotation.approvedBy ? [{ id: "2", title: "Commercial Approval Granted", description: `Approved by ${quotation.approvedBy}`, timestamp: quotation.createdAt, completed: true }] : []),
    ...(quotation.sentAt ? [{ id: "3", title: "Quotation Sent to Customer", description: `Delivered to ${quotation.contactEmail}`, timestamp: quotation.sentAt, completed: true }] : []),
    ...(quotation.acceptedAt ? [{ id: "4", title: "Quotation Accepted by Shipper", description: "Customer accepted commercial terms & grand total.", timestamp: quotation.acceptedAt, completed: true }] : []),
  ];

  const handleApprove = () => {
    approveQuotation(quotation.id, "Priya Nair (Sales Director)");
    toast.success(`Quotation ${quotation.quotationNumber} approved`);
  };

  const handleSend = () => {
    sendQuotation(quotation.id);
    toast.success(`Quotation ${quotation.quotationNumber} sent to ${quotation.contactEmail}`);
  };

  const handleAccept = () => {
    acceptQuotation(quotation.id);
    toast.success(`Quotation ${quotation.quotationNumber} marked as ACCEPTED!`);
  };

  const handleRejectSubmit = () => {
    rejectQuotation(quotation.id, rejectReason);
    toast.error(`Quotation ${quotation.quotationNumber} marked as Rejected.`);
    setIsRejectDialogOpen(false);
  };

  const handleRevisionSubmit = () => {
    const rev = createRevision(quotation.id, revisionReason);
    if (rev) {
      toast.success(`Created Revision ${rev.revisionNumber} for ${rev.quotationNumber}`);
      setIsRevisionDialogOpen(false);
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-300 pb-12">
      {/* Page Header */}
      <PageHeader
        title={`${quotation.quotationNumber} (Rev ${quotation.revisionNumber}): ${quotation.customerName}`}
        subtitle={`Route: ${quotation.origin} → ${quotation.destination} (${quotation.transportMode})`}
        breadcrumbs={[
          { label: "Sales & CRM", href: "/sales/crm" },
          { label: "Quotations", href: "/sales/quotations" },
          { label: quotation.quotationNumber },
        ]}
        statusBadge={<StatusBadge status={quotation.status} />}
        actions={
          <div className="flex items-center gap-2 flex-wrap">
            {quotation.status === "Pending Approval" && (
              <Button variant="primary" size="sm" icon={CheckCircle2} onClick={handleApprove}>
                Approve Quotation
              </Button>
            )}

            {(quotation.status === "Draft" || quotation.status === "Pending Approval") && (
              <Button variant="secondary" size="sm" icon={Send} onClick={handleSend}>
                Send to Customer
              </Button>
            )}

            {quotation.status === "Sent" && (
              <>
                <Button variant="primary" size="sm" icon={CheckCircle2} onClick={handleAccept}>
                  Customer Accept
                </Button>
                <Button variant="outline" size="sm" icon={XCircle} onClick={() => setIsRejectDialogOpen(true)}>
                  Customer Reject
                </Button>
              </>
            )}

            <Button variant="outline" size="sm" icon={History} onClick={() => setIsRevisionDialogOpen(true)}>
              Create Revision
            </Button>

            <Button variant="ghost" size="sm" icon={Printer} onClick={() => window.print()}>
              Print PDF
            </Button>

            {/* Create Operational Job Action */}
            {quotation.status === "Accepted" ? (
              <Link href={`/operations/jobs/create?quotationId=${quotation.id}`}>
                <Button variant="primary" size="sm" icon={Briefcase}>
                  Create Operational Job
                </Button>
              </Link>
            ) : (
              <Button variant="outline" size="sm" disabled icon={Briefcase} className="opacity-50">
                Job Creation (Accept Quote First)
              </Button>
            )}
          </div>
        }
      />

      {/* Primary Metric Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="p-4 flex items-center gap-3">
          <div className="p-3 rounded-lg bg-sky-500/10 text-sky-500 shrink-0">
            <DollarSign className="w-5 h-5" />
          </div>
          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase block">Customer Grand Total</span>
            <span className="font-mono font-bold text-slate-900 dark:text-slate-100 text-lg block">
              {formatCurrency(quotation.grandTotal)}
            </span>
            <span className="text-[11px] text-slate-400">Subtotal: {formatCurrency(quotation.subtotal)}</span>
          </div>
        </Card>

        <Card className="p-4 flex items-center gap-3">
          <div className="p-3 rounded-lg bg-blue-500/10 text-blue-500 shrink-0">
            <Building2 className="w-5 h-5" />
          </div>
          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase block">Shipper Customer</span>
            <span className="font-bold text-slate-900 dark:text-slate-100 text-sm block">{quotation.customerName}</span>
            <span className="text-[11px] text-slate-400">{quotation.contactName}</span>
          </div>
        </Card>

        <Card className="p-4 flex items-center gap-3">
          <div className="p-3 rounded-lg bg-emerald-500/10 text-emerald-500 shrink-0">
            <ArrowRight className="w-5 h-5" />
          </div>
          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase block">Route & Transit</span>
            <span className="font-bold text-slate-900 dark:text-slate-100 text-xs flex items-center gap-1">
              <span>{quotation.origin.split(" ")[0]}</span>
              <ArrowRight className="w-3 h-3 text-sky-500" />
              <span>{quotation.destination.split(" ")[0]}</span>
            </span>
            <span className="text-[11px] text-slate-400">{quotation.transitTime}</span>
          </div>
        </Card>

        <Card className="p-4 flex items-center gap-3">
          <div className="p-3 rounded-lg bg-amber-500/10 text-amber-500 shrink-0">
            <Calendar className="w-5 h-5" />
          </div>
          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase block">Validity & Terms</span>
            <span className="font-mono font-bold text-slate-900 dark:text-slate-100 text-xs block">
              Until {quotation.validUntil}
            </span>
            <span className="text-[11px] text-slate-400">{quotation.paymentTerms}</span>
          </div>
        </Card>
      </div>

      {/* Main Tabs Container */}
      <Card className="p-0 overflow-hidden">
        <div className="p-4 bg-slate-900/40 border-b border-slate-200 dark:border-slate-800">
          <Tabs
            tabs={[
              { id: "preview", label: "Customer Document Preview (PDF)" },
              { id: "internal", label: "Internal Profitability (Confidential)" },
              { id: "revisions", label: "Revision History", count: (quotation.revisions || []).length },
              { id: "timeline", label: "Activity Timeline", count: timelineActivities.length },
            ]}
            activeTab={activeTab}
            onChange={setActiveTab}
          />
        </div>

        <div className="p-6">
          {/* TAB 1: FORMAL CUSTOMER-FACING DOCUMENT PREVIEW */}
          {activeTab === "preview" && (
            <div className="max-w-4xl mx-auto p-8 rounded-lg bg-slate-950 border border-slate-800 space-y-6 text-xs shadow-2xl">
              {/* Document Header */}
              <div className="flex items-start justify-between border-b border-slate-800 pb-6">
                <div>
                  <h2 className="text-xl font-bold text-slate-100 tracking-wider">LOGISTICS OS FREIGHT</h2>
                  <p className="text-slate-400 text-[11px] mt-0.5">Enterprise Logistics Operating System</p>
                  <p className="text-slate-500 text-[10px]">Mumbai • Singapore • Dubai • Hamburg</p>
                </div>
                <div className="text-right">
                  <span className="text-lg font-mono font-bold text-sky-400">{quotation.quotationNumber}</span>
                  <p className="text-slate-400 text-[11px] font-medium">Revision {quotation.revisionNumber}</p>
                  <p className="text-slate-500 text-[11px]">Date: {quotation.createdAt}</p>
                  <p className="text-amber-400 text-[11px] font-mono">Valid Until: {quotation.validUntil}</p>
                </div>
              </div>

              {/* Customer & Route Details */}
              <div className="grid grid-cols-2 gap-6 p-4 rounded-lg bg-slate-900/50 border border-slate-800">
                <div className="space-y-1">
                  <span className="text-[10px] text-slate-500 font-bold uppercase block">Customer / Shipper</span>
                  <p className="font-bold text-slate-100 text-sm">{quotation.customerName}</p>
                  <p className="text-slate-400">{quotation.contactName}</p>
                  <p className="text-slate-400">{quotation.contactEmail} • {quotation.contactPhone}</p>
                </div>

                <div className="space-y-1">
                  <span className="text-[10px] text-slate-500 font-bold uppercase block">Shipment Specifications</span>
                  <p className="font-semibold text-slate-200">
                    Route: {quotation.origin} → {quotation.destination}
                  </p>
                  <p className="text-slate-400">Transport Mode: {quotation.transportMode} ({quotation.serviceType})</p>
                  <p className="text-slate-400">Transit Time: {quotation.transitTime} • Incoterm: {quotation.incoterm}</p>
                </div>
              </div>

              {/* Customer Line Items Table */}
              <div className="space-y-2">
                <h4 className="font-bold text-slate-200 uppercase text-[10px]">Commercial Rate Items</h4>
                <table className="w-full text-left border-collapse text-xs">
                  <thead>
                    <tr className="border-b border-slate-800 text-slate-500 uppercase text-[10px]">
                      <th className="py-2">Description</th>
                      <th className="py-2 text-center">Qty</th>
                      <th className="py-2 text-center">Unit</th>
                      <th className="py-2 text-right">Unit Price</th>
                      <th className="py-2 text-right">Total Price</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-850">
                    {quotation.items.map((item) => (
                      <tr key={item.id}>
                        <td className="py-2.5 font-medium text-slate-200">{item.description}</td>
                        <td className="py-2.5 text-center font-mono">{item.quantity}</td>
                        <td className="py-2.5 text-center text-slate-400">{item.unit}</td>
                        <td className="py-2.5 text-right font-mono">{formatCurrency(item.unitPrice)}</td>
                        <td className="py-2.5 text-right font-mono font-bold text-slate-100">{formatCurrency(item.totalPrice)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Financial Totals Block */}
              <div className="flex justify-end pt-4 border-t border-slate-800">
                <div className="w-72 space-y-2 text-xs">
                  <div className="flex justify-between">
                    <span className="text-slate-400">Subtotal:</span>
                    <span className="font-mono text-slate-200">{formatCurrency(quotation.subtotal)}</span>
                  </div>
                  {quotation.discountAmount > 0 && (
                    <div className="flex justify-between text-emerald-400">
                      <span>Commercial Discount:</span>
                      <span className="font-mono">-{formatCurrency(quotation.discountAmount)}</span>
                    </div>
                  )}
                  <div className="flex justify-between">
                    <span className="text-slate-400">{quotation.taxName} ({quotation.taxPercentage}%):</span>
                    <span className="font-mono text-slate-200">+{formatCurrency(quotation.taxAmount)}</span>
                  </div>
                  <div className="flex justify-between border-t border-slate-800 pt-2 text-sm font-bold">
                    <span className="text-slate-100">Grand Total:</span>
                    <span className="font-mono text-sky-400">{formatCurrency(quotation.grandTotal)}</span>
                  </div>
                </div>
              </div>

              {/* Terms & Conditions */}
              <div className="pt-4 border-t border-slate-800 text-[11px] text-slate-400 space-y-1">
                <span className="font-bold text-slate-300 block uppercase text-[10px]">Commercial Terms & Conditions</span>
                <p className="whitespace-pre-line">{quotation.termsAndConditions}</p>
              </div>
            </div>
          )}

          {/* TAB 2: INTERNAL CONFIDENTIAL PROFITABILITY */}
          {activeTab === "internal" && (
            <div className="space-y-4 text-xs">
              <div className="p-4 rounded-lg bg-amber-500/10 border border-amber-500/30 text-amber-400 flex items-start gap-2">
                <ShieldAlert className="w-5 h-5 shrink-0 mt-0.5" />
                <div>
                  <p className="font-bold text-sm">Confidential Internal Profitability Analysis</p>
                  <p className="text-xs text-amber-300/80 mt-1">
                    This section contains internal vendor cost breakdowns, margin calculations, and profit metrics. This data is **NEVER** displayed on the customer-facing quotation document.
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div className="p-3 rounded-lg bg-slate-900/60 border border-slate-800 space-y-1">
                  <span className="text-[10px] text-slate-400 font-bold uppercase block">Internal Estimated Cost</span>
                  <span className="font-mono font-bold text-slate-100 text-sm block">{formatCurrency(quotation.internalCost)}</span>
                </div>

                <div className="p-3 rounded-lg bg-slate-900/60 border border-slate-800 space-y-1">
                  <span className="text-[10px] text-slate-400 font-bold uppercase block">Customer Selling Subtotal</span>
                  <span className="font-mono font-bold text-slate-100 text-sm block">{formatCurrency(quotation.subtotal)}</span>
                </div>

                <div className="p-3 rounded-lg bg-emerald-950/30 border border-emerald-500/30 space-y-1">
                  <span className="text-[10px] text-emerald-400 font-bold uppercase block">Commercial Margin Profit</span>
                  <span className="font-mono font-bold text-emerald-400 text-sm block">+{formatCurrency(quotation.marginAmount)}</span>
                </div>

                <div className="p-3 rounded-lg bg-emerald-950/30 border border-emerald-500/30 space-y-1">
                  <span className="text-[10px] text-emerald-400 font-bold uppercase block">Margin Percentage</span>
                  <span className="font-mono font-bold text-emerald-400 text-sm block">{quotation.marginPercentage.toFixed(2)}%</span>
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: REVISIONS */}
          {activeTab === "revisions" && (
            <div className="space-y-3 text-xs max-w-2xl mx-auto">
              <h4 className="font-bold text-slate-200">Quotation Revision History Log</h4>
              {(quotation.revisions || []).map((rev) => (
                <div key={rev.revisionNumber} className="p-3 rounded-lg border border-slate-800 space-y-1">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-sky-400">Revision {rev.revisionNumber}</span>
                    <span className="font-mono text-slate-400">{rev.createdAt}</span>
                  </div>
                  <p className="text-slate-300">Reason: {rev.reason}</p>
                  <p className="text-slate-400">Grand Total: <strong className="text-slate-100 font-mono">{formatCurrency(rev.grandTotal)}</strong> (Margin: {formatCurrency(rev.marginAmount)})</p>
                </div>
              ))}
            </div>
          )}

          {/* TAB 4: TIMELINE */}
          {activeTab === "timeline" && (
            <div className="max-w-xl mx-auto py-2">
              <Timeline events={timelineActivities} />
            </div>
          )}
        </div>
      </Card>

      {/* REJECT DIALOG */}
      <Dialog
        isOpen={isRejectDialogOpen}
        onClose={() => setIsRejectDialogOpen(false)}
        title="Mark Quotation as Rejected"
        description={`Record customer rejection for ${quotation.quotationNumber}`}
      >
        <div className="space-y-4 py-2">
          <Input
            label="Rejection Reason"
            required
            placeholder="e.g. Customer selected competitor rate"
            value={rejectReason}
            onChange={(e) => setRejectReason(e.target.value)}
          />

          <div className="flex justify-end gap-2 pt-2">
            <Button variant="outline" size="sm" onClick={() => setIsRejectDialogOpen(false)}>
              Cancel
            </Button>
            <Button variant="primary" size="sm" onClick={handleRejectSubmit}>
              Confirm Rejection
            </Button>
          </div>
        </div>
      </Dialog>

      {/* REVISION DIALOG */}
      <Dialog
        isOpen={isRevisionDialogOpen}
        onClose={() => setIsRevisionDialogOpen(false)}
        title="Create New Quotation Revision"
        description={`Generate next revision (Rev ${quotation.revisionNumber + 1}) for ${quotation.quotationNumber}`}
      >
        <div className="space-y-4 py-2">
          <Input
            label="Revision Reason"
            required
            placeholder="e.g. Price negotiation: 5% discount requested"
            value={revisionReason}
            onChange={(e) => setRevisionReason(e.target.value)}
          />

          <div className="flex justify-end gap-2 pt-2">
            <Button variant="outline" size="sm" onClick={() => setIsRevisionDialogOpen(false)}>
              Cancel
            </Button>
            <Button variant="primary" size="sm" onClick={handleRevisionSubmit}>
              Create Revision
            </Button>
          </div>
        </div>
      </Dialog>
    </div>
  );
}
